version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Runtime environment variables
      PORT: 3000
      NODE_ENV: production
      BASE_PATH: /test
    volumes:
      - ./config/simpledir:/config
      - ./test:/test
    ports:
      - "3000:3000"
